version: "3.3"

services:
  traefik:
    image: traefik:v2.4
    container_name: inethi-traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ${INETHI_NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=${TRAEFIK_API_RULE}"
      - "traefik.http.routers.api.service=${TRAEFIK_API_SERVICE}"
      - "traefik.http.routers.api.entrypoints=${TRAEFIK_API_ENTRYPOINT}"
networks:
  web:
    external: true
