version: '3'

services:
  nginx:
    image: nginx
    container_name: inethi-splash-nginx
    restart: always
    volumes:
        - "${NGINX_VOLUME}/html:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=${TRAEFIK_RULE}"
      - "traefik.http.routers.nginx.entrypoints=${TRAEFIK_ENTRYPOINT}"
    networks:
      - "${INETHI_NETWORK}"
networks:
  web:
    external: true
